services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    command:  ["http", "frontend:3000"]
    environment:
      - NGROK_AUTHTOKEN=
    ports:
      - "4040:4040"
    depends_on:
      - backend
    tty: true
  frontend:
    build: frontend/.
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # (Remove the published port if Nginx is the entrypoint)

  backend:
    build: backend/.
    container_name: backend
    restart: always
    environment:
      - DB_HOST=mariadb
      - DB_USER=Byterush
      - DB_PASSWORD=Byterushpass
      - DB_NAME=Byterush
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Byterushroot
      MYSQL_DATABASE: Byterush
      MYSQL_USER: Byterush
      MYSQL_PASSWORD: Byterushpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
